name: CI

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: ${{ matrix.os }}/${{ matrix.ruby }}/${{ matrix.python }}-${{ matrix.python_architecture }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - macos-latest
        ruby:
        - "3.0"
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        python:
        - 3.x
        - 2.x
        python_architecture:
        - x64
        include:
        - { os: ubuntu-20.04 , ruby: 2.7 , python: 3.8 }
        - { os: ubuntu-20.04 , ruby: 2.7 , python: 3.7 }
        - { os: ubuntu-20.04 , ruby: 2.7 , python: 3.6 }
        - { os: ubuntu-18.04 , ruby: 2.7 , python: 3.8 }

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: ruby/setup-ruby@v1
      if: matrix.ruby_version != 'master-nightly'
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.python_architecture }}

    - run: pip install --user numpy

    - run: bundle install

    - run: bundle exec rake
      env:
        PYTHON: python

  conda:
    name: conda:${{ matrix.os }}/${{ matrix. ruby }}/${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - macos-latest
        ruby:
        - "3.0"
        python:
        - 3.8

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: ruby/setup-ruby@v1
      if: matrix.ruby_version != 'master-nightly'
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: s-weigand/setup-conda@v1
      with:
        python-version: ${{ matrix.python }}

    - run: conda install numpy

    - run: bundle install

    - run: bundle exec rake
      env:
        PYTHON: python

